config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cessda/cessda.fair-tests:
      branch: main
      repo: https://github.com/cessda/cessda.fair-tests.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cessda/cessda.fair-tests git:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-ochre-lemming.sh
        container: qc.acc_droopy-pear-bracke
  QC.Doc:
    repos:
      github.com/cessda/cessda.fair-tests find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-flax-woodpecker.sh
        container: qc.doc_tasty-azure-akita
      github.com/cessda/cessda.fair-tests git:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-yellow-loon.sh
        container: qc.doc_jumpy-copper-buffalo
      github.com/cessda/cessda.fair-tests markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-xanthic-lionfish.sh
        container: qc.doc_geeky-indigo-boar
  QC.Lic:
    repos:
      github.com/cessda/cessda.fair-tests licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-emerald-echidna.sh
        container: qc.lic_dorky-magnolia-eleuth
  QC.Met:
    repos:
      github.com/cessda/cessda.fair-tests cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-purple-opossum.sh
        container: qc.met_ready-bronze-cattle
  QC.Sty:
    repos:
      github.com/cessda/cessda.fair-tests checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-firebrick-monster.sh
        container: qc.sty_baggy-tan-nightingale
      github.com/cessda/cessda.fair-tests hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-alizarin-ocelot.sh
        container: qc.sty_stealthy-eggplant-starfish
  QC.Ver:
    repos:
      github.com/cessda/cessda.fair-tests get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-myrtle-shark.sh
        container: qc.ver_muggy-chocolate-dachshund
timeout: 5400
